#!/bin/bash
# adatok beolvasasa es tomb feltoltese
declare -a tomb=()
i=0
input="./kerdesek.txt"
while IFS= read -r line
do
tomb[i]=$line
i=$[i+1]
done < "$input"
i=$[i-5]
#random kerdes valsztas
y=$[i/6]
	sor=($(shuf -i 0-$y -n 16))
	echo "${sor[@]}"

#kezzdo osszeg
m=0
kilep=1
tel=0
koz=0
while [ "$kilep" != "16" ]
do
clear
printf "Legyen ön is milliomos!	                      "
printf '|%-4s|\n' "Jellenlegi nyeremény:"$m

printf "				|"${kilep}". KÉRDÉS!|                      H segítség"'\n'
echo
echo ${tomb[sor[kilep]*6]}
j=0
for j in 0 1 2 3
do
sleep 1
eval echo ${tomb[sor[kilep]*6+1+j]}
done
#megold
#eval echo ${tomb[sor[kilep]*5+4]}

#tomb
read -p "válasz: "  be
#utmutato
    if [ "${be^^}" == "H" ];then
        clear
        echo "Milliomos játékhoz a választ A,B,C,D karakterekkel adhatja meg."
        echo "Kis és nagy karakterekre nem érzékeny."
        echo "H karakter a játék útmutatójához."
        echo "Kettő segítség közül vállaszthat T mint telefonos"
        echo "K mint közönség mindegyiket egyszer használhatja." 
        echo "Kuris Dávid H3SQTV 2019"
        read -p "Enter a folytatáshoz.. "  be
        else
#telefonos segitseg mindig jo
            if [ "${be^^}" == "T" ];then
            if [ "${tel}" == "1" ];then
            echo "Már használtad ezt a segítséget"
            read -p "Enter a folytatáshoz.. "  be
            else
                tel=1
                echo "${tomb[sor[kilep]*6+5]}. válaszleehtőség szerintem."
    
            read -p "Enter a folytatáshoz.. "  be
            fi
            else
#kozonseg kerdes
            if [ "${be^^}" == "K" ];then
                if [ "${koz}" == "1" ];then
                echo "Már használtad ezt a segítséget"
                read -p "Enter a folytatáshoz.. "  be
                else

                koz=1
                ran=($(shuf -i 65-68 -n 4))
                elso=($(shuf -i 50-90 -n 1))
                printf "\x$(printf %x $[ran[0]]). válaszlehetőség $elso\n"
                #echo $[ran[0]]". válaszlehetőség "$elso"%"
                masodik=($(shuf -i 1-$[100-elso] -n 1))
                printf "\x$(printf %x $[ran[1]]). válaszlehetőség $masodik\n"
                harmadik=($(shuf -i 1-$[100-(masodik+elso)] -n 1))
                printf "\x$(printf %x $[ran[2]]). válaszlehetőség $harmadik\n"
                negyedik=$[100-(elso+masodik+harmadik)]
                printf "\x$(printf %x $[ran[3]]). válaszlehetőség $negyedik\n"
#"  
                read -p "Enter a folytatáshoz.. "  be
            fi
            else
#kiertekeles
                    if [ "${be^^}" == "${tomb[sor[kilep]*6+5]}"  ]; then
                    	echo "Helyes válasz!"
                    	sleep 2

                    if [ "$kilep" == "1" ]; then 
                    	m=5000
                    else
                    	m=$[m*2]
                    fi
                    	kilep=$[kilep+1]
                        if [ $kilep == "16" ]; then
                            echo "Gratulálunk megnyerte a főnyereményt!"
                            echo "Nyereménye:"$m
                            sleep 2

                        fi
                    else
                    	echo "Játék vége :("
                    	eval echo "Jó megoldás: " ${tomb[sor[kilep]*6+5]}
                    	kilep=16
                    	echo "Nyeremény: "$m
                fi
            fi
        fi
    fi
done
