#!/bin/bash
# adatok beolvasasa es tomb feltoltese
declare -a tomb=()
i=0
input="./kerdes.txt"
while IFS= read -r line
do
tomb[i]=$line
i=$i+1
done < "$input"

declare -a valasz=()
j=0
input="./valasz.txt"
while IFS= read -r line
do
valasz[j]=$line
j=$j+1
done < "$input"

#kezzdo osszeg
m=0
kilep=1
while [ "$kilep" != "15" ]
do
clear
printf "Legyen ön is milliomos!				 "
printf '|%-4s|\n' "Jellenlegi nyeremény:"$m
#random kerdes valsztas

	y=$i
	DIV=$((y))
	r=$(($RANDOM%$DIV))
	echo $r

#echo $r
printf "				|"${kilep}". KÉRDÉS!|"'\n'
echo
echo ${tomb[r]}
j=0
for j in 0 1 2 3
do
eval echo ${valasz[r*5+j]}
done
#megold
#eval echo ${valasz[r*5+4]}

#valasz
read -p "válasz: "  be

if [ "${be^^}" == "${valasz[r*5+4]}"  ]; then
	echo "Helyes válasz!"
	sleep 2

if [ "$kilep" == "1" ]; then
	m=5000
else
	m=$[m*2]
fi
	kilep=$[kilep+1]
else
	echo "Játék vége :("
	eval echo "Jó megoldás: " ${valasz[r*5+4]}
	kilep=15
	echo "Nyeremény: "$m
fi
done

#todo
#nyeremeny vesztes fix potok
#random ami volt mar ne legyen
#segitsegek
#help info jatekmenet
#megallas lehehoseg

